spring.application.name=moolacarb

spring.datasource.url=${jdbc_url}
spring.datasource.username=${db_user}
spring.datasource.password=${db_pass}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver